update contribution of Huggingface KREW
Pseudo-Lab/deep-learning-glossary pull request #5
Opened 2023-10-14 07:50 UTC by gabrielwithappy

# What does this PR do?
딥러닝에 사용되는 용어를 일관성있게 한국어로 번역하기 위한 용어사전을 만들기 위한 Pull Request 템플릿입니다.
인용한 자료가 있다면 경우 링크 연결이 필요합니다. 

## Who can review? (Initial)

## Before submitting
- [/] 로컬 웹브라우져로 자신이 수정한 변경사항을 확인하셨나요? Did you check a preview of the website with a local web browser?
- [-] 용어를 가져온 문서정보 링크를 업데이트 하셨나요? Did you add a link to the article you got the term from? 
- [-] 용어에 대한 설명을 작성 시 참고한 자료가 있다면 링크를 업데이트 해주세요. Please update the link if you have references to determine and describe the terminology.

## Who can review? (maintainer)
May you please review this PR? 
@sim-so, @gabrielwithappy, @jungnerd @jsshin2022

2023-10-14 07:51 UTC, gabrielwithappy commented
@sim-so @jungnerd  @jsshin2022 
각 팀의 홈페이지를 연결하기 위한 구조를 위와 같이 생각해봤습니다. HuggingfaceKREW 홈페이도 함께 연결했습니다.
리뷰 부탁드립니다.

2023-10-17 03:38 UTC, wonhyeongseo requested changes
안녕하세요, 성모님!

제 프로필을 채웠어요. 용어 사전을 구축해주셔서 감사합니다.
오늘도 행복한 하루 보내시길 바래요 😄

2023-10-17 03:38 UTC, wonhyeongseo commented on glossary/contribution.qmd
> +[Huggingface KREW](https://pseudo-lab.github.io/huggingface_krew/)는 허깅페이스를 이해하기 다양한 활동을 하고 있으며 허깅페이스 문서를 번역하는 과정에서 용어를 일관성 있게 번역하기 위해서 사전을 만들고 있습니다.
```suggestion
[Huggingface KREW](https://pseudo-lab.github.io/huggingface_krew/)는 허깅페이스를 이해하기 다양한 활동을 하고 있으며 허깅페이스 문서를 일관성 있게 번역하기 위해서 용어 사전을 만들고 있습니다.
```

2023-10-17 03:38 UTC, wonhyeongseo commented on glossary/contribution.qmd
>  | 서원형 |  Pseudo Lab. Huggingface KREW         |               |
```suggestion
| 서원형 |  Pseudo Lab. Huggingface KREW         |  [Github](https://github.com/wonhyeongseo)/[Linkedin](https://www.linkedin.com/in/wonhseo/)             |
```

2023-10-17 09:13 UTC, gabrielwithappy commented
리뷰 확인하여 merge 합니다. :-)

2023-10-17 09:13 UTC, merged